package com.example.feedbackservice.review.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.example.feedbackservice.review.converter.ReviewScoreConverter;

@DynamoDBTable(tableName = "review")
public class Review {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String message;

    @DynamoDBAttribute
    private String flightId;

    @DynamoDBAttribute
    private String operatorId;

    @DynamoDBTypeConverted(converter = ReviewScoreConverter.class)
    private ReviewScore score;

    public Review() {
    }

    public Review(String id,
                  String message,
                  String flightId,
                  String operatorId,
                  ReviewScore score) {
        this.id = id;
        this.message = message;
        this.flightId = flightId;
        this.operatorId = operatorId;
        this.score = score;
    }


    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getFlightId() {
        return flightId;
    }

    public void setFlightId(String flightId) {
        this.flightId = flightId;
    }

    public String getOperatorId() {
        return operatorId;
    }

    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId;
    }

    public ReviewScore getScore() {
        return score;
    }

    public void setScore(ReviewScore score) {
        this.score = score;
    }
}
