server:
  port: 8082
external:
  api:
    tarom:
      baseurl: http://localhost:8083/tarom
    lufthansa:
      baseurl: http://localhost:8084/lufthansa
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9081/realms/FlightsBookingApp
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
keycloak:
  client-id: flights-booking-app
jwt:
  auth:
    converter:
      resource-id: flights-booking-app
      principle-attribute: preferred_username