package com.example.feedbackservice.feedback.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.example.feedbackservice.converter.FeedbackTypeConverter;

@DynamoDBTable(tableName = "feedback")
public class Feedback {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String message;

    @DynamoDBAttribute
    private String flightId;

    @DynamoDBAttribute
    private String bookingId;

    @DynamoDBTypeConverted(converter = FeedbackTypeConverter.class)
    private FeedbackType type;

    public Feedback() {
    }

    public Feedback(String id,
                    String message,
                    String flightId,
                    String bookingId,
                    FeedbackType type) {
        this.id = id;
        this.message = message;
        this.flightId = flightId;
        this.bookingId = bookingId;
        this.type = type;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getFlightId() {
        return flightId;
    }

    public void setFlightId(String flightId) {
        this.flightId = flightId;
    }

    public String getBookingId() {
        return bookingId;
    }

    public void setBookingId(String bookingId) {
        this.bookingId = bookingId;
    }

    public FeedbackType getType() {
        return type;
    }

    public void setType(FeedbackType type) {
        this.type = type;
    }
}
